// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActivity = `-- name: CreateActivity :one
INSERT INTO activity (id, workspace_id, user_id, board_id, column_id, card_id, comment_id, tag_id, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, workspace_id, user_id, board_id, column_id, card_id, comment_id, tag_id, description, created_at
`

type CreateActivityParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspaceId"`
	UserID      pgtype.UUID `json:"userId"`
	BoardID     pgtype.UUID `json:"boardId"`
	ColumnID    pgtype.UUID `json:"columnId"`
	CardID      pgtype.UUID `json:"cardId"`
	CommentID   pgtype.UUID `json:"commentId"`
	TagID       pgtype.UUID `json:"tagId"`
	Description string      `json:"description"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.ID,
		arg.WorkspaceID,
		arg.UserID,
		arg.BoardID,
		arg.ColumnID,
		arg.CardID,
		arg.CommentID,
		arg.TagID,
		arg.Description,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.BoardID,
		&i.ColumnID,
		&i.CardID,
		&i.CommentID,
		&i.TagID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getActivityByID = `-- name: GetActivityByID :one
SELECT id, workspace_id, user_id, board_id, column_id, card_id, comment_id, tag_id, description, created_at FROM activity
WHERE id = $1
`

func (q *Queries) GetActivityByID(ctx context.Context, id pgtype.UUID) (Activity, error) {
	row := q.db.QueryRow(ctx, getActivityByID, id)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.BoardID,
		&i.ColumnID,
		&i.CardID,
		&i.CommentID,
		&i.TagID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getBoardActivity = `-- name: GetBoardActivity :many
SELECT id, workspace_id, user_id, board_id, column_id, card_id, comment_id, tag_id, description, created_at FROM activity
WHERE workspace_id = $1
  AND board_id     = $2
  AND ($3::uuid    IS NULL OR card_id = $3)
  AND ($4::uuid    IS NULL OR user_id = $4)
  AND ($5::timestamptz IS NULL OR created_at > $5)
  AND ($6::timestamptz IS NULL OR created_at < $6)
ORDER BY created_at DESC
`

type GetBoardActivityParams struct {
	WorkspaceID pgtype.UUID        `json:"workspaceId"`
	BoardID     pgtype.UUID        `json:"boardId"`
	Column3     pgtype.UUID        `json:"column3"`
	Column4     pgtype.UUID        `json:"column4"`
	Column5     pgtype.Timestamptz `json:"column5"`
	Column6     pgtype.Timestamptz `json:"column6"`
}

func (q *Queries) GetBoardActivity(ctx context.Context, arg GetBoardActivityParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, getBoardActivity,
		arg.WorkspaceID,
		arg.BoardID,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.BoardID,
			&i.ColumnID,
			&i.CardID,
			&i.CommentID,
			&i.TagID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardActivity = `-- name: GetCardActivity :many
SELECT id, workspace_id, user_id, board_id, column_id, card_id, comment_id, tag_id, description, created_at FROM activity
WHERE card_id    = $1
  AND ($2::uuid  IS NULL OR user_id = $2)
  AND ($3::timestamptz IS NULL OR created_at > $3)
  AND ($4::timestamptz IS NULL OR created_at < $4)
ORDER BY created_at DESC
`

type GetCardActivityParams struct {
	CardID  pgtype.UUID        `json:"cardId"`
	Column2 pgtype.UUID        `json:"column2"`
	Column3 pgtype.Timestamptz `json:"column3"`
	Column4 pgtype.Timestamptz `json:"column4"`
}

func (q *Queries) GetCardActivity(ctx context.Context, arg GetCardActivityParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, getCardActivity,
		arg.CardID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.BoardID,
			&i.ColumnID,
			&i.CardID,
			&i.CommentID,
			&i.TagID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceActivity = `-- name: GetWorkspaceActivity :many
SELECT id, workspace_id, user_id, board_id, column_id, card_id, comment_id, tag_id, description, created_at FROM activity
WHERE workspace_id = $1
  AND ($2::uuid    IS NULL OR board_id = $2)
  AND ($3::uuid    IS NULL OR card_id  = $3)
  AND ($4::uuid    IS NULL OR user_id  = $4)
  AND ($5::timestamptz IS NULL OR created_at > $5)
  AND ($6::timestamptz IS NULL OR created_at < $6)
ORDER BY created_at DESC
`

type GetWorkspaceActivityParams struct {
	WorkspaceID pgtype.UUID        `json:"workspaceId"`
	Column2     pgtype.UUID        `json:"column2"`
	Column3     pgtype.UUID        `json:"column3"`
	Column4     pgtype.UUID        `json:"column4"`
	Column5     pgtype.Timestamptz `json:"column5"`
	Column6     pgtype.Timestamptz `json:"column6"`
}

func (q *Queries) GetWorkspaceActivity(ctx context.Context, arg GetWorkspaceActivityParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, getWorkspaceActivity,
		arg.WorkspaceID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.BoardID,
			&i.ColumnID,
			&i.CardID,
			&i.CommentID,
			&i.TagID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
