// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: boards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBoard = `-- name: CreateBoard :one
INSERT INTO board (id, title, description, prefix, workspace_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, description, prefix, sequence, is_archived, workspace_id, created_at, updated_at
`

type CreateBoardParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description *string     `json:"description"`
	Prefix      string      `json:"prefix"`
	WorkspaceID pgtype.UUID `json:"workspaceId"`
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, createBoard,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Prefix,
		arg.WorkspaceID,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Prefix,
		&i.Sequence,
		&i.IsArchived,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBoard = `-- name: DeleteBoard :exec
DELETE FROM board
WHERE id = $1
`

func (q *Queries) DeleteBoard(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBoard, id)
	return err
}

const getBoardByID = `-- name: GetBoardByID :one
SELECT id, title, description, prefix, sequence, is_archived, workspace_id, created_at, updated_at FROM board
WHERE id = $1
`

func (q *Queries) GetBoardByID(ctx context.Context, id pgtype.UUID) (Board, error) {
	row := q.db.QueryRow(ctx, getBoardByID, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Prefix,
		&i.Sequence,
		&i.IsArchived,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBoardsByWorkspace = `-- name: GetBoardsByWorkspace :many
SELECT id, title, description, prefix, sequence, is_archived, workspace_id, created_at, updated_at FROM board
WHERE workspace_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetBoardsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]Board, error) {
	rows, err := q.db.Query(ctx, getBoardsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Board
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Prefix,
			&i.Sequence,
			&i.IsArchived,
			&i.WorkspaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementBoardSequence = `-- name: IncrementBoardSequence :one
UPDATE board
SET sequence = sequence + 1
WHERE id = $1
RETURNING sequence
`

func (q *Queries) IncrementBoardSequence(ctx context.Context, id pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementBoardSequence, id)
	var sequence int32
	err := row.Scan(&sequence)
	return sequence, err
}

const updateBoard = `-- name: UpdateBoard :one
UPDATE board
SET title       = COALESCE($2, title),
    description = COALESCE($3, description),
    is_archived = COALESCE($4, is_archived),
    updated_at  = current_timestamp
WHERE id = $1
RETURNING id, title, description, prefix, sequence, is_archived, workspace_id, created_at, updated_at
`

type UpdateBoardParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description *string     `json:"description"`
	IsArchived  bool        `json:"isArchived"`
}

func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, updateBoard,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.IsArchived,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Prefix,
		&i.Sequence,
		&i.IsArchived,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
