// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCardTag = `-- name: AddCardTag :exec
INSERT INTO card_tag (card_id, tag_id)
VALUES ($1, $2)
`

type AddCardTagParams struct {
	CardID pgtype.UUID `json:"cardId"`
	TagID  pgtype.UUID `json:"tagId"`
}

func (q *Queries) AddCardTag(ctx context.Context, arg AddCardTagParams) error {
	_, err := q.db.Exec(ctx, addCardTag, arg.CardID, arg.TagID)
	return err
}

const createCard = `-- name: CreateCard :one
INSERT INTO card (id, title, description, position, reference, workspace_id, board_id, column_id, user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, title, description, is_archived, position, reference, workspace_id, board_id, column_id, user_id, created_at, updated_at
`

type CreateCardParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description *string     `json:"description"`
	Position    float32     `json:"position"`
	Reference   string      `json:"reference"`
	WorkspaceID pgtype.UUID `json:"workspaceId"`
	BoardID     pgtype.UUID `json:"boardId"`
	ColumnID    pgtype.UUID `json:"columnId"`
	UserID      pgtype.UUID `json:"userId"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Position,
		arg.Reference,
		arg.WorkspaceID,
		arg.BoardID,
		arg.ColumnID,
		arg.UserID,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsArchived,
		&i.Position,
		&i.Reference,
		&i.WorkspaceID,
		&i.BoardID,
		&i.ColumnID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM card
WHERE id = $1
`

func (q *Queries) DeleteCard(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCard, id)
	return err
}

const getCardByID = `-- name: GetCardByID :one
SELECT id, title, description, is_archived, position, reference, workspace_id, board_id, column_id, user_id, created_at, updated_at FROM card
WHERE id = $1
`

func (q *Queries) GetCardByID(ctx context.Context, id pgtype.UUID) (Card, error) {
	row := q.db.QueryRow(ctx, getCardByID, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsArchived,
		&i.Position,
		&i.Reference,
		&i.WorkspaceID,
		&i.BoardID,
		&i.ColumnID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCardTags = `-- name: GetCardTags :many
SELECT t.id, t.name, t.color, t.workspace_id, t.created_at, t.updated_at FROM tag t
JOIN card_tag ct ON ct.tag_id = t.id
WHERE ct.card_id = $1
`

func (q *Queries) GetCardTags(ctx context.Context, cardID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getCardTags, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.WorkspaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardsByBoard = `-- name: GetCardsByBoard :many
SELECT id, title, description, is_archived, position, reference, workspace_id, board_id, column_id, user_id, created_at, updated_at FROM card
WHERE board_id = $1
ORDER BY position ASC
`

func (q *Queries) GetCardsByBoard(ctx context.Context, boardID pgtype.UUID) ([]Card, error) {
	rows, err := q.db.Query(ctx, getCardsByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.IsArchived,
			&i.Position,
			&i.Reference,
			&i.WorkspaceID,
			&i.BoardID,
			&i.ColumnID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllCardTags = `-- name: RemoveAllCardTags :exec
DELETE FROM card_tag
WHERE card_id = $1
`

func (q *Queries) RemoveAllCardTags(ctx context.Context, cardID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeAllCardTags, cardID)
	return err
}

const removeCardTag = `-- name: RemoveCardTag :exec
DELETE FROM card_tag
WHERE card_id = $1
  AND tag_id = $2
`

type RemoveCardTagParams struct {
	CardID pgtype.UUID `json:"cardId"`
	TagID  pgtype.UUID `json:"tagId"`
}

func (q *Queries) RemoveCardTag(ctx context.Context, arg RemoveCardTagParams) error {
	_, err := q.db.Exec(ctx, removeCardTag, arg.CardID, arg.TagID)
	return err
}

const updateCard = `-- name: UpdateCard :one
UPDATE card
SET title       = COALESCE($2, title),
    description = COALESCE($3, description),
    is_archived = COALESCE($4, is_archived),
    position    = COALESCE($5, position),
    column_id   = COALESCE($6, column_id),
    user_id     = COALESCE($7, user_id),
    updated_at  = current_timestamp
WHERE id = $1
RETURNING id, title, description, is_archived, position, reference, workspace_id, board_id, column_id, user_id, created_at, updated_at
`

type UpdateCardParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description *string     `json:"description"`
	IsArchived  bool        `json:"isArchived"`
	Position    float32     `json:"position"`
	ColumnID    pgtype.UUID `json:"columnId"`
	UserID      pgtype.UUID `json:"userId"`
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, updateCard,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.IsArchived,
		arg.Position,
		arg.ColumnID,
		arg.UserID,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsArchived,
		&i.Position,
		&i.Reference,
		&i.WorkspaceID,
		&i.BoardID,
		&i.ColumnID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
