// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: columns.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createColumn = `-- name: CreateColumn :one
INSERT INTO kb_column (id, title, wip_limit, color, is_terminal, position, board_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, wip_limit, color, is_terminal, position, board_id, created_at, updated_at
`

type CreateColumnParams struct {
	ID         pgtype.UUID `json:"id"`
	Title      string      `json:"title"`
	WipLimit   *int32      `json:"wipLimit"`
	Color      interface{} `json:"color"`
	IsTerminal bool        `json:"isTerminal"`
	Position   int32       `json:"position"`
	BoardID    pgtype.UUID `json:"boardId"`
}

func (q *Queries) CreateColumn(ctx context.Context, arg CreateColumnParams) (KbColumn, error) {
	row := q.db.QueryRow(ctx, createColumn,
		arg.ID,
		arg.Title,
		arg.WipLimit,
		arg.Color,
		arg.IsTerminal,
		arg.Position,
		arg.BoardID,
	)
	var i KbColumn
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.WipLimit,
		&i.Color,
		&i.IsTerminal,
		&i.Position,
		&i.BoardID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteColumn = `-- name: DeleteColumn :exec
DELETE FROM kb_column
WHERE id = $1
`

func (q *Queries) DeleteColumn(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteColumn, id)
	return err
}

const getColumnByID = `-- name: GetColumnByID :one
SELECT id, title, wip_limit, color, is_terminal, position, board_id, created_at, updated_at FROM kb_column
WHERE id = $1
`

func (q *Queries) GetColumnByID(ctx context.Context, id pgtype.UUID) (KbColumn, error) {
	row := q.db.QueryRow(ctx, getColumnByID, id)
	var i KbColumn
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.WipLimit,
		&i.Color,
		&i.IsTerminal,
		&i.Position,
		&i.BoardID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getColumnsByBoard = `-- name: GetColumnsByBoard :many
SELECT id, title, wip_limit, color, is_terminal, position, board_id, created_at, updated_at FROM kb_column
WHERE board_id = $1
ORDER BY position ASC
`

func (q *Queries) GetColumnsByBoard(ctx context.Context, boardID pgtype.UUID) ([]KbColumn, error) {
	rows, err := q.db.Query(ctx, getColumnsByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KbColumn
	for rows.Next() {
		var i KbColumn
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.WipLimit,
			&i.Color,
			&i.IsTerminal,
			&i.Position,
			&i.BoardID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateColumn = `-- name: UpdateColumn :one
UPDATE kb_column
SET title       = COALESCE($2, title),
    wip_limit   = COALESCE($3, wip_limit),
    color       = COALESCE($4, color),
    is_terminal = COALESCE($5, is_terminal),
    position    = COALESCE($6, position),
    updated_at  = current_timestamp
WHERE id = $1
RETURNING id, title, wip_limit, color, is_terminal, position, board_id, created_at, updated_at
`

type UpdateColumnParams struct {
	ID         pgtype.UUID `json:"id"`
	Title      string      `json:"title"`
	WipLimit   *int32      `json:"wipLimit"`
	Color      interface{} `json:"color"`
	IsTerminal bool        `json:"isTerminal"`
	Position   int32       `json:"position"`
}

func (q *Queries) UpdateColumn(ctx context.Context, arg UpdateColumnParams) (KbColumn, error) {
	row := q.db.QueryRow(ctx, updateColumn,
		arg.ID,
		arg.Title,
		arg.WipLimit,
		arg.Color,
		arg.IsTerminal,
		arg.Position,
	)
	var i KbColumn
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.WipLimit,
		&i.Color,
		&i.IsTerminal,
		&i.Position,
		&i.BoardID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
