// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comment (id, body, card_id, user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, body, card_id, user_id, created_at, updated_at
`

type CreateCommentParams struct {
	ID     pgtype.UUID `json:"id"`
	Body   string      `json:"body"`
	CardID pgtype.UUID `json:"cardId"`
	UserID pgtype.UUID `json:"userId"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ID,
		arg.Body,
		arg.CardID,
		arg.UserID,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.CardID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comment
WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, body, card_id, user_id, created_at, updated_at FROM comment
WHERE id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id pgtype.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.CardID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommentsByCard = `-- name: GetCommentsByCard :many
SELECT id, body, card_id, user_id, created_at, updated_at FROM comment
WHERE card_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetCommentsByCard(ctx context.Context, cardID pgtype.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, getCommentsByCard, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.CardID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comment
SET body       = $2,
    updated_at = current_timestamp
WHERE id = $1
RETURNING id, body, card_id, user_id, created_at, updated_at
`

type UpdateCommentParams struct {
	ID   pgtype.UUID `json:"id"`
	Body string      `json:"body"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.ID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.CardID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
