// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Role string

const (
	RoleOwner       Role = "owner"
	RoleAdmin       Role = "admin"
	RoleContributer Role = "contributer"
	RoleViewer      Role = "viewer"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role `json:"role"`
	Valid bool `json:"valid"` // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type Activity struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspaceId"`
	UserID      pgtype.UUID        `json:"userId"`
	BoardID     pgtype.UUID        `json:"boardId"`
	ColumnID    pgtype.UUID        `json:"columnId"`
	CardID      pgtype.UUID        `json:"cardId"`
	CommentID   pgtype.UUID        `json:"commentId"`
	TagID       pgtype.UUID        `json:"tagId"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
}

type Board struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	Prefix      string             `json:"prefix"`
	Sequence    int32              `json:"sequence"`
	IsArchived  bool               `json:"isArchived"`
	WorkspaceID pgtype.UUID        `json:"workspaceId"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type Card struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	IsArchived  bool               `json:"isArchived"`
	Position    float32            `json:"position"`
	Reference   string             `json:"reference"`
	WorkspaceID pgtype.UUID        `json:"workspaceId"`
	BoardID     pgtype.UUID        `json:"boardId"`
	ColumnID    pgtype.UUID        `json:"columnId"`
	UserID      pgtype.UUID        `json:"userId"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type CardTag struct {
	CardID pgtype.UUID `json:"cardId"`
	TagID  pgtype.UUID `json:"tagId"`
}

type Comment struct {
	ID        pgtype.UUID        `json:"id"`
	Body      string             `json:"body"`
	CardID    pgtype.UUID        `json:"cardId"`
	UserID    pgtype.UUID        `json:"userId"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type KbColumn struct {
	ID         pgtype.UUID        `json:"id"`
	Title      string             `json:"title"`
	WipLimit   *int32             `json:"wipLimit"`
	Color      interface{}        `json:"color"`
	IsTerminal bool               `json:"isTerminal"`
	Position   int32              `json:"position"`
	BoardID    pgtype.UUID        `json:"boardId"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt  pgtype.Timestamptz `json:"updatedAt"`
}

type KbUser struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"passwordHash"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

type Tag struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Color       interface{}        `json:"color"`
	WorkspaceID pgtype.UUID        `json:"workspaceId"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type Workspace struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	OwnerID     pgtype.UUID        `json:"ownerId"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type WorkspaceUser struct {
	UserID      pgtype.UUID `json:"userId"`
	WorkspaceID pgtype.UUID `json:"workspaceId"`
	Pending     bool        `json:"pending"`
	Role        Role        `json:"role"`
}
