// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tag (id, name, color, workspace_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, color, workspace_id, created_at, updated_at
`

type CreateTagParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Color       interface{} `json:"color"`
	WorkspaceID pgtype.UUID `json:"workspaceId"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.WorkspaceID,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tag
WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name, color, workspace_id, created_at, updated_at FROM tag
WHERE id = $1
`

func (q *Queries) GetTagByID(ctx context.Context, id pgtype.UUID) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagsByWorkspace = `-- name: GetTagsByWorkspace :many
SELECT id, name, color, workspace_id, created_at, updated_at FROM tag
WHERE workspace_id = $1
ORDER BY name ASC
`

func (q *Queries) GetTagsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTagsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.WorkspaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :one
UPDATE tag
SET name       = COALESCE($2, name),
    color      = COALESCE($3, color),
    updated_at = current_timestamp
WHERE id = $1
RETURNING id, name, color, workspace_id, created_at, updated_at
`

type UpdateTagParams struct {
	ID    pgtype.UUID `json:"id"`
	Name  string      `json:"name"`
	Color interface{} `json:"color"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.ID, arg.Name, arg.Color)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
