// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspace (id, title, description, owner_id)
VALUES ($1, $2, $3, $4)
RETURNING id, title, description, owner_id, created_at, updated_at
`

type CreateWorkspaceParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description *string     `json:"description"`
	OwnerID     pgtype.UUID `json:"ownerId"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.OwnerID,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspace
WHERE id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkspace, id)
	return err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, title, description, owner_id, created_at, updated_at FROM workspace
WHERE id = $1
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id pgtype.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspacesByUser = `-- name: GetWorkspacesByUser :many
SELECT w.id, w.title, w.description, w.owner_id, w.created_at, w.updated_at FROM workspace w
JOIN workspace_user wu ON wu.workspace_id = w.id
WHERE wu.user_id = $1
  AND wu.pending = false
UNION
SELECT id, title, description, owner_id, created_at, updated_at FROM workspace
WHERE owner_id = $1
`

func (q *Queries) GetWorkspacesByUser(ctx context.Context, userID pgtype.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, getWorkspacesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspace
SET title       = COALESCE($2, title),
    description = COALESCE($3, description),
    updated_at  = current_timestamp
WHERE id = $1
RETURNING id, title, description, owner_id, created_at, updated_at
`

type UpdateWorkspaceParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description *string     `json:"description"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace, arg.ID, arg.Title, arg.Description)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
