// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_members.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :exec
INSERT INTO workspace_user (user_id, workspace_id, role, pending)
VALUES ($1, $2, $3, false)
`

type AddWorkspaceMemberParams struct {
	UserID      pgtype.UUID `json:"userId"`
	WorkspaceID pgtype.UUID `json:"workspaceId"`
	Role        Role        `json:"role"`
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, addWorkspaceMember, arg.UserID, arg.WorkspaceID, arg.Role)
	return err
}

const getWorkspaceMember = `-- name: GetWorkspaceMember :one
SELECT u.id, u.name, u.email, u.created_at, wu.role
FROM workspace_user wu
JOIN kb_user u ON u.id = wu.user_id
WHERE wu.workspace_id = $1
  AND wu.user_id = $2
`

type GetWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID `json:"workspaceId"`
	UserID      pgtype.UUID `json:"userId"`
}

type GetWorkspaceMemberRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	Role      Role               `json:"role"`
}

func (q *Queries) GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (GetWorkspaceMemberRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var i GetWorkspaceMemberRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const getWorkspaceMembers = `-- name: GetWorkspaceMembers :many
SELECT u.id, u.name, u.email, u.created_at, wu.role
FROM workspace_user wu
JOIN kb_user u ON u.id = wu.user_id
WHERE wu.workspace_id = $1
  AND wu.pending = false
`

type GetWorkspaceMembersRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	Role      Role               `json:"role"`
}

func (q *Queries) GetWorkspaceMembers(ctx context.Context, workspaceID pgtype.UUID) ([]GetWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, getWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorkspaceMembersRow
	for rows.Next() {
		var i GetWorkspaceMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceMembership = `-- name: GetWorkspaceMembership :one
SELECT user_id, workspace_id, pending, role FROM workspace_user
WHERE workspace_id = $1
  AND user_id = $2
`

type GetWorkspaceMembershipParams struct {
	WorkspaceID pgtype.UUID `json:"workspaceId"`
	UserID      pgtype.UUID `json:"userId"`
}

func (q *Queries) GetWorkspaceMembership(ctx context.Context, arg GetWorkspaceMembershipParams) (WorkspaceUser, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMembership, arg.WorkspaceID, arg.UserID)
	var i WorkspaceUser
	err := row.Scan(
		&i.UserID,
		&i.WorkspaceID,
		&i.Pending,
		&i.Role,
	)
	return i, err
}

const removeWorkspaceMember = `-- name: RemoveWorkspaceMember :exec
DELETE FROM workspace_user
WHERE workspace_id = $1
  AND user_id = $2
`

type RemoveWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID `json:"workspaceId"`
	UserID      pgtype.UUID `json:"userId"`
}

func (q *Queries) RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, removeWorkspaceMember, arg.WorkspaceID, arg.UserID)
	return err
}

const updateWorkspaceMemberRole = `-- name: UpdateWorkspaceMemberRole :exec
UPDATE workspace_user
SET role = $3
WHERE workspace_id = $1
  AND user_id = $2
`

type UpdateWorkspaceMemberRoleParams struct {
	WorkspaceID pgtype.UUID `json:"workspaceId"`
	UserID      pgtype.UUID `json:"userId"`
	Role        Role        `json:"role"`
}

func (q *Queries) UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateWorkspaceMemberRole, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}
